# SwiftLint Configuration for Clean Code

disabled_rules:
  - trailing_whitespace
  - line_length
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fallthrough
  - force_unwrapping
  - implicit_getter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

excluded:
  - Pods
  - DerivedData
  - .build
  - Tests
  - Scripts
  - vendor
  - fastlane
  - R.generated.swift
  - BuildTools

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - url
    - uri

custom_rules:
  marks_empty_space:
    name: "MARK with empty space"
    regex: '\/\/ MARK: [^\s]'
    message: "Add empty space after MARK:"
    severity: warning
