name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Install Dependencies
      run: |
        # pod install # Uncomment if using CocoaPods
        echo "Dependencies installed"
        
    - name: Build
      run: |
        xcodebuild clean build \
          -scheme VirtuAI \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          
    - name: Run Tests
      run: |
        xcodebuild test \
          -scheme VirtuAI \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
